// react-counter/src/components/counter/index.jsx
import React, {useState } from 'react';
import Button from '../button';
import './index.css';

const Counter = () => {
  const [count, setCount] = useState(0);
  const [history, setHistory] = useState([]);

  const increment = () => {
    setCount(count + 1);
    history.push('Increment');
  };

  const decrement = () => {
    setCount(count - 1);
    history.push('Decrement');
  };

  const reset = () => {
    setHistory([]);
    setCount(0);
  }

  const onInputChange = (evt) => {
    setCount(parseInt(evt.target.value));
  }

  const getCountValueClasses = () => {
    let classes = "count__value";
    
    if (count > 0) {
      classes += " count__value--positive";
    } else if (count < 0) {
      classes += " count__value--negative";
    }

    return classes;
  }

  return (
    <div className="counter">
      <h2 className="counter__title">Dummy Counter</h2>
      <div className="count">
        <Button clickHandler={() => decrement()} disabled={count <= -5}>-</Button>
        <input className={getCountValueClasses()} value={count} onChange={onInputChange} type="number" />
        <Button clickHandler={() => increment()}>+</Button>
      </div>
     { history.length > 0
        ? (
            <div className="history">
              <h3>Your history:</h3>
              {
                history.map((operation, index) => (
                  <p className="history__entry" key={index}>{operation}</p>
                ))
              }
              <Button clickHandler={() => reset()}>
                Reset
              </Button>
            </div>
          )
        : <p>No history found</p>
      }
    </div>
  );
};

export default Counter;

// vue-counter/solutions/Counter.vue
<template>
  <div class="counter">
    <h2 class="counter__title">Dummy Counter</h2>
      <div class="count">
        <CustomButton @on-click="decrement" :disabled="count <= -5">-</CustomButton>
        <input :class="getCountValueClasses" v-model.number="count" type="number"/>
        <CustomButton @on-click="increment">+</CustomButton>
      </div>
      <div v-if="historyExists" class="history">
        <h3>Your history:</h3>
         <p
          v-for="(operation, index) in history"
          class="history__entry"
          :key="index"
        >
          {{ operation }}
        </p>
        <CustomButton @on-click="reset">
          Reset
        </CustomButton>
      </div>
      <p v-else>No history found</p>
  </div>
</template>

<script>
import CustomButton from './CustomButton.vue';

export default {
  components: {
    CustomButton,
  },
  data () {
    return {
      count: 0,
      history: []
    }
  },
  methods: {
    increment() {
      this.count++;
      this.history.push('Increment');
    },
    decrement() {
      this.count--;
      this.history.push('Decrement');
    },
    reset() {
      this.count = 0;
      this.history = []
    },
  },
  computed: {
    getCountValueClasses() {
      return [
        'count__value',
        {
          'count__value--positive': this.count > 0,
          'count__value--negative': this.count < 0
        }
      ];
    },
    historyExists() {
      return this.history.length > 0;
    }
  }
}
</script>

<style scoped>
/* .cta::v-deep {
  padding: 10px 20px;
} */

.counter {
  padding: 50px 0px;
}

.counter__title {
  margin-top: 0px;
}

.count__value {
  font-size: 1.2rem;
  text-align: center;
  margin: 0 1rem;
}

.count__value--positive {
  border: 2px solid green;
  color: green;
}

.count__value--negative {
  border: 2px solid red;
  color: red;
}

.history {
  margin-top: 30px;
}

.history__entry {
  font-size: 1.2rem;
}
</style>
